FILMARO:
  source_url: 'https://github.com/Venca24/filmaro/'

LANGS:
  available_locales:
    cs: 'Čeština'
    de: 'Deutsch'
    en: 'English'
    eo: 'Esperanto'
    es: 'Español'
    fr: 'Français'

  default_locale: :en

ITEMS:
  # id + template
  Q11424: :film # film
  Q24862: :film # short film
  Q24869: :film # feature film
  Q226730: :film # silent film
  Q506240: :film # television film
  Q229390: :film # 3D film
  Q17517379: :film # animated short film
  Q20667187: :film # silent short film
  Q29168811: :film # animated feature film
